site_name: UCchip Docs
site_url: https://example.com/
nav:
    - 关于御芯微: 'index.md'
    - UCCHIP集成开发环境:
        - 'UCCHIP IDE 安装': ucchip_env/UCCHIP_IDE_install.md
        - '编译下载': ucchip_env/build_and_down.md
        - '调试': ucchip_env/debug.md
    - MCU:
        - '概览':   mcu/introduction_mcu.md
        - 'UC8088': 
          - 'UC8088系列介绍': mcu/uc8088/introduction_uc8088.md
          - 'UC8088总线结构': mcu/uc8088/uc8088_bus.md
          - 'UC8088存储': mcu/uc8088/uc8088_memmap.md
          - 'UC8088时钟树': mcu/uc8088/uc8088_clk.md
          - 'UC8088电源控制': mcu/uc8088/uc8088_pwr.md
          - 'UC8088中断控制': mcu/uc8088/uc8088_event.md
        - 'UC8288': 
          - 'UC8288系列介绍': mcu/uc8288/introduction_uc8288.md
          - 'UC8288总线结构': mcu/uc8288/uc8288_bus.md
          - 'UC8288存储': mcu/uc8288/uc8288_memmap.md
          - 'UC8288时钟树': mcu/uc8288/uc8288_clk.md
          - 'UC8288电源控制': mcu/uc8288/uc8288_pwr.md
          - 'UC8288中断控制': mcu/uc8288/uc8288_event.md
        - 'UC8888': mcu/mcu_uc8888.md
        - '外设':
          - 'PWM': MCU/imperio/pwm/pwm.md
          - 'WATCHDOG': MCU/imperio/watchdog/watchdog.md
          - 'I2C': MCU/imperio/i2c/i2c.md
          - 'GPIO': MCU/imperio/gpio/gpio.md
          - 'ADC': MCU/imperio/adc/adc.md
          - 'DAC': MCU/imperio/dac/dac.md
          - 'PMU': MCU/imperio/pmu/lowpower.md
          - 'TRNG': MCU/imperio/trng/trng.md
          - 'EVTC': MCU/imperio/evtc/evtc.md
          - 'FLASG': MCU/imperio/flash/flash.md
          - 'SPIM': MCU/imperio/spimaster/spimaster.md
          - 'RTC': MCU/imperio/rtc/rtc.md
          - '外设控制器': MCU/imperio/peripheralcontrol/peripheral.md
          - 'TIMER': MCU/imperio/timer/timer.md
          - 'UART': MCU/imperio/uart/uart.md
          - 'UDMA': MCU/imperio/udma/udma.md
    - 蜂窝:
        - '概览':   3gpp/introduction_3gpp.md
        - 'UC8088': 3gpp/3gpp_uc8088.md
        - 'UC8066': 3gpp/3gpp_uc8066.md
        - 'UCM800': 3gpp/3gpp_ucm800.md
        - 'UCM868': 3gpp/3gpp_ucm868.md
    - LPWAN:
        - '概览':   wiota/introduction_wiota.md
        - 'UC8288': wiota/wiota_uc8288.md
        - 'UC8666': wiota/wiota_uc8666.md
    - GNSS:
        - '概览':   gnss/introduction_gnss.md
        - 'UC8088': gnss/gnss_uc8088.md
        - 'UC8888': gnss/gnss_uc8888.md
        - 'UCM800': gnss/gnss_ucm800.md
        - 'UCM868': gnss/gnss_ucm868.md
    - RFID:
        - '概览':   rfid/introduction_rfid.md
        - 'UC8689': rfid/rfid_uc8689.md
        - 'UCM868': rfid/rfid_ucm868.md
    - Connectivety:
        - '概览':   Connectivety/introduction_connectivety.md
        - 'UC8266': Connectivety/connectivety_uc8266.md
    - About: 'about.md'
theme:
  name: material
